Traceback (most recent call last):
  File "/home/runner/.local/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/runner/.local/lib/python3.10/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/runner/.local/lib/python3.10/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/runner/.local/lib/python3.10/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/home/runner/.local/lib/python3.10/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/home/runner/.local/lib/python3.10/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/runner/.local/lib/python3.10/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
result = divide(1, 0)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mAssertionError[0m                            Traceback (most recent call last)
Cell [0;32mIn[87], line 1[0m
[0;32m----> 1[0m result [38;5;241m=[39m [43mdivide[49m[43m([49m[38;5;241;43m1[39;49m[43m,[49m[43m [49m[38;5;241;43m0[39;49m[43m)[49m

Cell [0;32mIn[86], line 2[0m, in [0;36mdivide[0;34m(dividend, divisor)[0m
[1;32m      1[0m [38;5;28;01mdef[39;00m [38;5;21mdivide[39m(dividend, divisor):
[0;32m----> 2[0m     [38;5;28;01massert[39;00m divisor [38;5;241m!=[39m [38;5;241m0[39m, [38;5;124m"[39m[38;5;124mDivision by zero not valid![39m[38;5;124m"[39m
[1;32m      3[0m     [38;5;28;01mreturn[39;00m dividend[38;5;241m/[39mdivisor

[0;31mAssertionError[0m: Division by zero not valid!
AssertionError: Division by zero not valid!

